"""empty message

Revision ID: 615cdcb2d91e
Revises: a49c2b91c431
Create Date: 2022-04-07 21:45:12.806575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615cdcb2d91e'
down_revision = 'a49c2b91c431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
