# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
 tests:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Set up Python 3.9.8
     uses: actions/setup-python@v3
     with: 
       python-versions: "3.9.8"
   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
   - name: Lint
     run:
       flake8 app
   - name: Tests
     run: |
       cd app
       python -m pytest ../tests
 build:
   runs-on: ubuntu-latest
   steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v3

     # Runs a single command using the runners shell
     - name: Run a one-line script
       run: echo Hello, world!

     # Runs a set of commands using the runners shell
     - name: Run a multi-line script
       run: |
         echo Add other actions to build,
         echo test, and deploy your project.
